import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { QueryClientProvider } from '@/providers/QueryClientProvider';
import NextAuthSessionProvider from '@/components/AuthProvider';
import './globals.css';
import { SmoothScroll } from '@/components/smooth-scroll';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-stone-50 via-amber-50 to-orange-50`}>
				<SmoothScroll />
				<NextAuthSessionProvider>
					
				<QueryClientProvider>{children}</QueryClientProvider>
				</NextAuthSessionProvider>
			</body>
		</html>
	);
}
